@base_url = http://localhost:8081
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA4MTkyNTB9.xG8NzCdzflit2747ZYuzH8bg1Sect_5WTP4su2oWQ38
POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text":"test 1"
}